apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: kill-healthy-every-5m
  namespace: demo
spec:
  schedule: "*/5 * * * *"
  type: PodChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces: [demo]
      labelSelectors:
        app: healthy-app
